server:
  port: 9100

spring:
  application:
    name: permission

  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 20
      connection-timeout: 2000
      connection-test-query: SELECT 1
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5

  main:
    allow-bean-definition-overriding: true

# mybatis
mybatis:
  typeAliasesPackage: com.spring.boot.permission.mapper
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

swagger:
  api:
    description: 权限管理服务

hystrisfeign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    endpoint:
      health:
        show-details: ALWAYS

info:
  app:
    name: permission
  company:
    name: yudr
  build:
    artifactId: $project.artifactId$
    version: $project.version$